-- SocialHub database setup for Supabase
-- Kør hele denne fil i Supabase → SQL Editor → Run.
-- Den opretter tabeller, RLS policies, realtime og en auth-trigger til profiler.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(trim(username)) between 2 and 24),
  is_online boolean not null default false,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.global_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  content text not null check (char_length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.private_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  sender_username text not null,
  receiver_username text not null,
  content text not null check (char_length(trim(content)) between 1 and 500),
  created_at timestamptz not null default now(),
  check (sender_id <> receiver_id)
);

create index if not exists profiles_username_idx on public.profiles (lower(username));
create index if not exists profiles_online_idx on public.profiles (is_online, last_seen desc);
create index if not exists global_messages_created_at_idx on public.global_messages (created_at desc);
create index if not exists global_messages_user_id_idx on public.global_messages (user_id);
create index if not exists private_messages_conversation_idx on public.private_messages (sender_id, receiver_id, created_at);
create index if not exists private_messages_receiver_idx on public.private_messages (receiver_id, created_at);

create or replace function public.socialhub_normalize_username(raw_value text)
returns text
language plpgsql
as $$
declare
  normalized text;
begin
  normalized := coalesce(trim(raw_value), '');
  normalized := regexp_replace(normalized, '^@+', '');
  normalized := regexp_replace(normalized, '\s+', '_', 'g');
  normalized := regexp_replace(normalized, '[^a-zA-Z0-9_æøåÆØÅ-]', '', 'g');
  normalized := left(normalized, 24);

  if char_length(normalized) < 2 then
    return '';
  end if;

  return normalized;
end;
$$;

create or replace function public.handle_new_socialhub_user()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  base_username text;
  candidate_username text;
  suffix text;
  counter integer := 0;
begin
  base_username := public.socialhub_normalize_username(new.raw_user_meta_data ->> 'username');

  if base_username = '' then
    base_username := public.socialhub_normalize_username(split_part(coalesce(new.email, ''), '@', 1));
  end if;

  if base_username = '' then
    base_username := 'bruger';
  end if;

  candidate_username := base_username;

  while exists (
    select 1 from public.profiles where lower(username) = lower(candidate_username)
  ) loop
    counter := counter + 1;
    suffix := '_' || substr(replace(new.id::text, '-', ''), greatest(1, counter), 4);
    candidate_username := left(base_username, greatest(2, 24 - char_length(suffix))) || suffix;

    if counter > 20 then
      candidate_username := 'bruger_' || substr(replace(new.id::text, '-', ''), 1, 8);
      exit;
    end if;
  end loop;

  insert into public.profiles (id, username, is_online, last_seen)
  values (new.id, candidate_username, false, now())
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created_socialhub on auth.users;
create trigger on_auth_user_created_socialhub
  after insert on auth.users
  for each row execute function public.handle_new_socialhub_user();

alter table public.profiles enable row level security;
alter table public.global_messages enable row level security;
alter table public.private_messages enable row level security;

-- Profiles policies
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
  on public.profiles for select
  to authenticated
  using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles for insert
  to authenticated
  with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

-- Global chat policies
drop policy if exists "global_messages_select_authenticated" on public.global_messages;
create policy "global_messages_select_authenticated"
  on public.global_messages for select
  to authenticated
  using (true);

drop policy if exists "global_messages_insert_own" on public.global_messages;
create policy "global_messages_insert_own"
  on public.global_messages for insert
  to authenticated
  with check (user_id = auth.uid());

drop policy if exists "global_messages_delete_own" on public.global_messages;
create policy "global_messages_delete_own"
  on public.global_messages for delete
  to authenticated
  using (user_id = auth.uid());

-- Private chat policies
drop policy if exists "private_messages_select_participants" on public.private_messages;
create policy "private_messages_select_participants"
  on public.private_messages for select
  to authenticated
  using (sender_id = auth.uid() or receiver_id = auth.uid());

drop policy if exists "private_messages_insert_sender" on public.private_messages;
create policy "private_messages_insert_sender"
  on public.private_messages for insert
  to authenticated
  with check (
    sender_id = auth.uid()
    and exists (select 1 from public.profiles where id = receiver_id)
  );

drop policy if exists "private_messages_delete_sender" on public.private_messages;
create policy "private_messages_delete_sender"
  on public.private_messages for delete
  to authenticated
  using (sender_id = auth.uid());

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.global_messages to authenticated;
grant select, insert, update, delete on public.private_messages to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.profiles replica identity full;
alter table public.global_messages replica identity full;
alter table public.private_messages replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.global_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.private_messages;
exception
  when duplicate_object then null;
  when undefined_object then null;
end $$;
