-- SocialHub message cleanup - slet beskeder der er ældre end 1 uge
-- Kør denne fil i Supabase → SQL Editor → Run
-- Dette script opretter en funktion og trigger der automatisk sletter gamle beskeder hver dag

-- Slet beskederne direkte først hvis du vil rydde op
-- DELETE FROM public.global_messages WHERE created_at < NOW() - INTERVAL '7 days';
-- DELETE FROM public.private_messages WHERE created_at < NOW() - INTERVAL '7 days';

-- Opret en funktion der sletter gamle beskeder
create or replace function public.cleanup_old_messages()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Slet global chat beskeder ældre end 7 dage
  delete from public.global_messages
  where created_at < now() - interval '7 days';

  -- Slet private chat beskeder ældre end 7 dage
  delete from public.private_messages
  where created_at < now() - interval '7 days';
end;
$$;

-- Opret en tabel for at track cleanup jobs
create table if not exists public.cleanup_log (
  id bigint generated by default as identity primary key,
  last_run timestamptz not null default now(),
  messages_deleted_global bigint default 0,
  messages_deleted_private bigint default 0
);

-- Grant permissions
grant execute on function public.cleanup_old_messages() to service_role;

-- MANUEL SETUP: Du skal selv køre cleanup-funktionen ved hjælp af en cron job eller en timer
-- 
-- OPTION 1: Cron job via pg_cron (hvis aktiveret på dit Supabase-projekt):
-- 
-- create or replace function public.cleanup_old_messages_with_logging()
-- returns void
-- language plpgsql
-- security definer
-- set search_path = public
-- as $$
-- declare
--   v_global_count bigint := 0;
--   v_private_count bigint := 0;
-- begin
--   delete from public.global_messages
--   where created_at < now() - interval '7 days'
--   returning count(*) into v_global_count;
--
--   delete from public.private_messages
--   where created_at < now() - interval '7 days'
--   returning count(*) into v_private_count;
--
--   insert into public.cleanup_log (last_run, messages_deleted_global, messages_deleted_private)
--   values (now(), v_global_count, v_private_count);
-- end;
-- $$;
--
-- select cron.schedule('cleanup_socialhub_messages', '0 2 * * *', 'select public.cleanup_old_messages_with_logging()');
--
-- OPTION 2: Manuelt - kør denne kommando en gang i dag i Supabase SQL Editor:
-- SELECT public.cleanup_old_messages();
--
-- OPTION 3: Du kan kalde denne funktion fra app.js ved app-start (se app.js for implementering)
